"""Composable fiber photometry analysis."""

from fiberphotometry.config import EventAnalysisConfig
from fiberphotometry.design import (
    Factor,
    ObservationTable,
    StudyDesign,
    Unit,
    validate_design,
)
from fiberphotometry.event_qc import assess_event_confounds
from fiberphotometry.events import align_events, summarize_event_windows
from fiberphotometry.inference import (
    Contrast,
    Estimand,
    InferenceRecommendation,
    PermutationPlan,
    ResamplingPlan,
    TIntervalResult,
    exact_sign_flip_test,
    hierarchical_bootstrap,
    permutation_test,
    recommend_inference,
    unit_t_interval,
)
from fiberphotometry.model import make_recording, validate_recording
from fiberphotometry.multiverse import (
    ChoiceRef,
    CompatibilityRule,
    DecisionAlternative,
    DecisionNode,
    DecisionSummary,
    LeaveOneOutResult,
    MaterializedUniverse,
    MultiverseResult,
    MultiverseSpec,
    RobustnessSummary,
    UniverseResult,
    materialize_multiverse,
    run_multiverse,
)
from fiberphotometry.pipeline import (
    BaselineDFFOperation,
    EventSummarySpec,
    LowpassFilterOperation,
    PipelineResult,
    PipelineSpec,
    PreprocessingSpec,
    QualityGateSpec,
    RecordingInput,
    ReferenceDFFOperation,
    ResampleOperation,
    run_pipeline,
)
from fiberphotometry.planning import (
    AnalysisPlan,
    AnalysisResult,
    PowerSensitivity,
    create_analysis_plan,
    execute_analysis_plan,
    welch_power_sensitivity,
)
from fiberphotometry.preprocess import (
    baseline_dff,
    lowpass_filter,
    reference_dff,
    resample_recording,
)
from fiberphotometry.qc import assess_recording, assess_signal_recording
from fiberphotometry.workflow import (
    EventAnalysis,
    EventAnalysisResult,
    EventSession,
    Preprocessing,
)

__all__ = [
    "AnalysisPlan",
    "AnalysisResult",
    "BaselineDFFOperation",
    "ChoiceRef",
    "CompatibilityRule",
    "Contrast",
    "DecisionAlternative",
    "DecisionNode",
    "DecisionSummary",
    "Estimand",
    "EventAnalysis",
    "EventAnalysisConfig",
    "EventAnalysisResult",
    "EventSession",
    "EventSummarySpec",
    "Factor",
    "InferenceRecommendation",
    "LeaveOneOutResult",
    "LowpassFilterOperation",
    "MaterializedUniverse",
    "MultiverseResult",
    "MultiverseSpec",
    "ObservationTable",
    "PermutationPlan",
    "PipelineResult",
    "PipelineSpec",
    "PowerSensitivity",
    "Preprocessing",
    "PreprocessingSpec",
    "QualityGateSpec",
    "RecordingInput",
    "ReferenceDFFOperation",
    "ResampleOperation",
    "ResamplingPlan",
    "RobustnessSummary",
    "StudyDesign",
    "TIntervalResult",
    "Unit",
    "UniverseResult",
    "align_events",
    "assess_event_confounds",
    "assess_recording",
    "assess_signal_recording",
    "baseline_dff",
    "create_analysis_plan",
    "exact_sign_flip_test",
    "execute_analysis_plan",
    "hierarchical_bootstrap",
    "lowpass_filter",
    "make_recording",
    "materialize_multiverse",
    "permutation_test",
    "recommend_inference",
    "reference_dff",
    "resample_recording",
    "run_multiverse",
    "run_pipeline",
    "summarize_event_windows",
    "unit_t_interval",
    "validate_design",
    "validate_recording",
    "welch_power_sensitivity",
]
