"""Composable fiber photometry analysis."""

from fiberphotometry.compatibility import (
    CompatibilityIssue,
    MultiverseCompatibility,
    PipelineCompatibility,
    UniverseCompatibility,
    assess_multiverse_compatibility,
    assess_pipeline_compatibility,
)
from fiberphotometry.config import EventAnalysisConfig
from fiberphotometry.design import (
    Factor,
    ObservationTable,
    StudyDesign,
    Unit,
    validate_design,
)
from fiberphotometry.event_qc import assess_event_confounds
from fiberphotometry.events import align_events, summarize_event_windows
from fiberphotometry.inference import (
    Contrast,
    Estimand,
    InferenceRecommendation,
    PermutationPlan,
    ResamplingPlan,
    TIntervalResult,
    exact_sign_flip_test,
    hierarchical_bootstrap,
    permutation_test,
    recommend_inference,
    unit_t_interval,
)
from fiberphotometry.io.nwb_project import export_project_nwb
from fiberphotometry.io.tabular import (
    TabularChannel,
    TabularChannelInspection,
    TabularEventColumn,
    TabularEventInspection,
    TabularEvents,
    TabularEventSchema,
    TabularInputInspection,
    TabularInspection,
    TabularRecordingSchema,
    inspect_loaded_tabular_input,
    inspect_tabular_input,
    inspect_tabular_recording,
    load_tabular_events,
    load_tabular_input,
    load_tabular_recording,
)
from fiberphotometry.io.tdt import (
    TDTBlockSchema,
    TDTEpocEvents,
    TDTEpocValue,
    TDTStreamChannel,
    load_tdt_input,
)
from fiberphotometry.metadata import (
    MetadataCheck,
    MetadataCompletenessReport,
    MetadataReadiness,
    assess_metadata_completeness,
)
from fiberphotometry.mixed import (
    ScalarMixedModelResult,
    ScalarMixedModelSpec,
    fit_scalar_mixed_model,
)
from fiberphotometry.model import make_recording, validate_recording
from fiberphotometry.multiverse import (
    ChoiceRef,
    CompatibilityRule,
    DecisionAlternative,
    DecisionNode,
    DecisionSummary,
    LeaveOneOutResult,
    MaterializedUniverse,
    MultiverseReportGroup,
    MultiverseResult,
    MultiverseSpec,
    RobustnessSummary,
    UniverseResult,
    materialize_multiverse,
    run_multiverse,
)
from fiberphotometry.pipeline import (
    BaselineDFFOperation,
    EventSummarySpec,
    LowpassFilterOperation,
    PipelineResult,
    PipelineSpec,
    PreprocessingSpec,
    QualityGateSpec,
    RecordingInput,
    ReferenceDFFOperation,
    ResampleOperation,
    run_pipeline,
)
from fiberphotometry.planning import (
    AnalysisPlan,
    AnalysisResult,
    PowerSensitivity,
    create_analysis_plan,
    execute_analysis_plan,
    welch_power_sensitivity,
)
from fiberphotometry.preprocess import (
    baseline_dff,
    lowpass_filter,
    reference_dff,
    resample_recording,
)
from fiberphotometry.project import (
    LoadedTabularProject,
    NWBExportConfig,
    ProjectConfig,
    TabularProjectConfig,
    TabularSessionSource,
    TDTProjectConfig,
    TDTSessionSource,
    load_project_config,
)
from fiberphotometry.qc import assess_recording, assess_signal_recording
from fiberphotometry.workflow import (
    EventAnalysis,
    EventAnalysisResult,
    EventSession,
    Preprocessing,
)

__all__ = [
    "AnalysisPlan",
    "AnalysisResult",
    "BaselineDFFOperation",
    "ChoiceRef",
    "CompatibilityIssue",
    "CompatibilityRule",
    "Contrast",
    "DecisionAlternative",
    "DecisionNode",
    "DecisionSummary",
    "Estimand",
    "EventAnalysis",
    "EventAnalysisConfig",
    "EventAnalysisResult",
    "EventSession",
    "EventSummarySpec",
    "Factor",
    "InferenceRecommendation",
    "LeaveOneOutResult",
    "LoadedTabularProject",
    "LowpassFilterOperation",
    "MaterializedUniverse",
    "MetadataCheck",
    "MetadataCompletenessReport",
    "MetadataReadiness",
    "MultiverseCompatibility",
    "MultiverseReportGroup",
    "MultiverseResult",
    "MultiverseSpec",
    "NWBExportConfig",
    "ObservationTable",
    "PermutationPlan",
    "PipelineCompatibility",
    "PipelineResult",
    "PipelineSpec",
    "PowerSensitivity",
    "Preprocessing",
    "PreprocessingSpec",
    "ProjectConfig",
    "QualityGateSpec",
    "RecordingInput",
    "ReferenceDFFOperation",
    "ResampleOperation",
    "ResamplingPlan",
    "RobustnessSummary",
    "ScalarMixedModelResult",
    "ScalarMixedModelSpec",
    "StudyDesign",
    "TDTBlockSchema",
    "TDTEpocEvents",
    "TDTEpocValue",
    "TDTProjectConfig",
    "TDTSessionSource",
    "TDTStreamChannel",
    "TIntervalResult",
    "TabularChannel",
    "TabularChannelInspection",
    "TabularEventColumn",
    "TabularEventInspection",
    "TabularEventSchema",
    "TabularEvents",
    "TabularInputInspection",
    "TabularInspection",
    "TabularProjectConfig",
    "TabularRecordingSchema",
    "TabularSessionSource",
    "Unit",
    "UniverseCompatibility",
    "UniverseResult",
    "align_events",
    "assess_event_confounds",
    "assess_metadata_completeness",
    "assess_multiverse_compatibility",
    "assess_pipeline_compatibility",
    "assess_recording",
    "assess_signal_recording",
    "baseline_dff",
    "create_analysis_plan",
    "exact_sign_flip_test",
    "execute_analysis_plan",
    "export_project_nwb",
    "fit_scalar_mixed_model",
    "hierarchical_bootstrap",
    "inspect_loaded_tabular_input",
    "inspect_tabular_input",
    "inspect_tabular_recording",
    "load_project_config",
    "load_tabular_events",
    "load_tabular_input",
    "load_tabular_recording",
    "load_tdt_input",
    "lowpass_filter",
    "make_recording",
    "materialize_multiverse",
    "permutation_test",
    "recommend_inference",
    "reference_dff",
    "resample_recording",
    "run_multiverse",
    "run_pipeline",
    "summarize_event_windows",
    "unit_t_interval",
    "validate_design",
    "validate_recording",
    "welch_power_sensitivity",
]
